### PR TITLE
Chore - more instance types

### PR DESCRIPTION
**Pull request by chpl**
### Problem

Our node group fails to scale with following error

```
Launching a new EC2 instance. Status Reason: Could not launch Spot Instances.
UnfulfillableCapacity - Unable to fulfill capacity due to your request configuration.
Please adjust your request and try again. Launching EC2 instance failed.
```

### Solution
Add more instance types to choose from

### CODE REVIEW

**Comment by Wassap124** [comment]
Why would more types solve the issue?

**Comment by Wassap124** [comment]
what would dictate which type would be used?

**Comment by chpl** [comment]
@Wassap124 

> Why would more types solve the issue?

There more instances to choose from when single instance type is unavailable - see [here](https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/spot-best-practices.html#be-instance-type-flexible). 

> what would dictate which type would be used?

similar to the type we already use

**Comment by Wassap124** [comment]
> similar to the type we already use

what does that mean?

**Review by Wassap124 — APPROVED** [review]
approving to unblock

**Comment by chpl** [comment]
@Wassap124

we use `t3a.2xlarge` instances - AMD processor 8 cores 32GB

I added
- `t3a.xlarge` which is AMD processor 4 cores and 16GB
- `t3` family of same sizes - intel CPU

**Pull request merged**
